In [16]:
import numpy as np
import pandas as pd
#working with series first
#series are just like array they hold the data but unlike array series can store different datatype like list,aray,dictonary  and it store the value
#in vertical form
#creating a series
arr =np.array([11,22,33,44])
l =["achar","biscuit","namkeen","toffee"]
d = {1:3,2:4,3:12,4:15}
#we can add custom index
data = pd.Series(l,index= arr)
data
# data =pd.Series(arr)
# data

11      achar
22    biscuit
33    namkeen
44     toffee
dtype: str

In [6]:
#now datafra

In [8]:
#data frames are the multiple series combination
import numpy as np
import pandas as pd
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data) #in dictonary as a dataframe the table heading name,age city and salary  came because in dictonary the value are stored as key value
# pair and in series the data comes in key value frame.

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
#pd.DataFrame(data_list)
#here the heading didnt came we have to manually add those things 
#Steps to add these heading are 
column =["name","age","city","salary"]
d = pd.DataFrame(data_list,columns = column)
d
#note :- only columns works column does not work

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
#now selection of indexing and removing of index value and adding of coulmn

In [20]:
d

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
#selecting of index - we give header value to access the value from index
d["name"]

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [24]:
#if multiple header want to access then use []
d[["name","salary"]]

    name  salary
0   John   65000
1   Anna   70000
2  Peter   62000
3  Linda   85000

In [25]:
#adding of column
#if we want to add column then we should create a list 
d["car"] =["honda","bmw","toyota","mistubishi"]

In [26]:
d # there is a catch if you didnt make the list size =  record section then it will give error

    name  age      city  salary         car
0   John   28  New York   65000       honda
1   Anna   34     Paris   70000         bmw
2  Peter   29    Berlin   62000      toyota
3  Linda   42    London   85000  mistubishi

In [28]:
#now deleting of record row-wise and column wise
d.drop("car",axis=1)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
#here we need to give axis for which row and column we need to delete the thing but using drop only show the tempropary changes the changes are not
#permanent for that we need to use inplace
d.drop(0,axis =0,inplace =True)

KeyError: '[0] not found in axis'

In [37]:
d

    name  age    city  salary         car
1   Anna   34   Paris   70000         bmw
2  Peter   29  Berlin   62000      toyota
3  Linda   42  London   85000  mistubishi

In [39]:
#now row wise
# selection row wise we use loc
d.loc[1]

name       Anna
age          34
city      Paris
salary    70000
car         bmw
Name: 1, dtype: object

In [40]:
#selection if subset of row and column same like in numpy
d.loc[[2,3]][["name","age"]]

    name  age
2  Peter   29
3  Linda   42

In [42]:
d
#conditional section 
# includes >< =& |
# select the age which is greater than 30
# the logic is similar of that numpy concept

    name  age    city  salary         car
1   Anna   34   Paris   70000         bmw
2  Peter   29  Berlin   62000      toyota
3  Linda   42  London   85000  mistubishi

In [43]:
d[d["age"]>30]

    name  age    city  salary         car
1   Anna   34   Paris   70000         bmw
3  Linda   42  London   85000  mistubishi

In [44]:
#now using of and operator
#select the age> 30 and city paris

In [45]:
d[(d["age"]>30) & (d["city"]== "Paris")]

   name  age   city  salary  car
1  Anna   34  Paris   70000  bmw